AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  board-auth

  Sample SAM Template for board-auth
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'POST, GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    EndpointConfiguration:
      Type: REGIONAL
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    MemorySize: 2048
    VpcConfig:
      SecurityGroupIds:
        - sg-0e49305eaea21b57a
      SubnetIds:
        - subnet-0cb72c20bdbd6392d
    Environment:
      Variables:
        JWT_ISSUER: ${JWT_ISSUER}
        JWT_SECRET: ${JWT_SECRET}
        HOSTNAME: ${HOSTNAME}
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
        DATABASE: ${DATABASE}

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: app.login
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoginApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"
  LoginFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt LoginFunction.Arn
  LoginFunctionIamRole:
    Description: "Implicit IAM Role created for Login function"
    Value: !GetAtt LoginFunctionRole.Arn