AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ISSUER:
    Type: String
    Default: "no_issuer"
  SECRET:
    Type: String
    Default: "no_secret"
  DATABASE:
    Type: String
    Default: "no_db"
  HOSTNAME:
    Type: String
    Default: "no_host"
  USERNAME:
    Type: String
    Default: "no_user"
  PASSWORD:
    Type: String
    Default: "no_pass"
  DYNAMODB:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Cors:
      AllowMethods: "'POST, GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    EndpointConfiguration:
      Type: REGIONAL
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: "'*'"
  Function:
    Timeout: 30
    Runtime: nodejs22.x
    MemorySize: 2048
    VpcConfig:
      SecurityGroupIds:
        - sg-0e49305eaea21b57a
      SubnetIds:
        - subnet-0cb72c20bdbd6392d
    Environment:
      Variables:
        ISSUER: !Ref ISSUER
        SECRET: !Ref SECRET
        DATABASE: !Ref DATABASE
        HOSTNAME: !Ref HOSTNAME
        USERNAME: !Ref USERNAME
        PASSWORD: !Ref PASSWORD
        DYNAMODB: !Ref DYNAMODB

Resources:
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./auth
      Handler: app.login
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DYNAMODB
        - VPCAccessPolicy: {}
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
  RefreshFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: app.refresh
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTableName
      Events:
        Login:
          Type: Api
          Properties:
            Path: /refresh
            Method: post
  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auth/
      Handler: app.logout
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTableName
      Events:
        Login:
          Type: Api
          Properties:
            Path: /logout
            Method: post


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoginApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login/"
  LoginFunction:
    Description: "Login Lambda Function ARN"
    Value: !GetAtt LoginFunction.Arn
  LoginFunctionIamRole:
    Description: "Implicit IAM Role created for Login function"
    Value: !GetAtt LoginFunctionRole.Arn