name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Node.js 버전에 맞게 수정

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2 # AWS 리전에 맞게 수정

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Install dependencies manually
        run: |
          cd auth
          npm ci
          echo "Dependencies installed:"
          ls -la node_modules/

      - name: Build for dev
        run: sam build -t dev.yaml && sam deploy -t dev.yaml --config-env dev --parameter-overrides " DYNAMODB=${{ secrets.DYNAMODB }}  ISSUER=${{ secrets.JWT_ISSUER }} SECRET=${{ secrets.JWT_SECRET }} DATABASE=${{ secrets.DATABASE }} HOSTNAME=${{ secrets.HOSTNAME }} USERNAME=${{ secrets.USERNAME }} PASSWORD=${{ secrets.PASSWORD }}"

